const replaceRouteParams = (rawRoute: string, routeParams: Record<string, string|number|null>): string => {Object.entries(routeParams).forEach(([key, value]) => rawRoute = rawRoute.replace(`{${key}}`, value as string)); return rawRoute;}
const appendQueryParams = (route: string, queryParams?: Record<string, string|number>): string => queryParams ? route + "?" + new URLSearchParams(queryParams as Record<string, string>).toString() : route;
export const path_user_route = (): { relative: (routeParams: {id:string, noteId:string}, queryParams?: Record<string, string>) => string, } => {return {relative: (routeParams: {id:string, noteId:string}, queryParams?: Record<string, string>): string => appendQueryParams(replaceRouteParams('/user/{id}/notes/{noteId}', routeParams), queryParams), }};
export const path_user_route_http = (): { relative: (routeParams: {id:string, noteId:string}, queryParams?: Record<string, string>) => string, } => {return {relative: (routeParams: {id:string, noteId:string}, queryParams?: Record<string, string>): string => appendQueryParams(replaceRouteParams('/user/{id}/notes/{noteId}', routeParams), queryParams), }};
export const path_user_route_without_scheme = (): { relative: (routeParams: {id:string, noteId:string}, queryParams?: Record<string, string>) => string, } => {return {relative: (routeParams: {id:string, noteId:string}, queryParams?: Record<string, string>): string => appendQueryParams(replaceRouteParams('/user/{id}/notes/{noteId}', routeParams), queryParams), }};
export const path_users_route_without_requirements_and_defaults = (): { relative: (queryParams?: Record<string, string>) => string, } => {return {relative: (queryParams?: Record<string, string>): string => appendQueryParams('/users', queryParams), }};
export const path_users_route_with_requirements = (): { relative: (routeParams: {id:number, locale:'en'|'fr'}, queryParams?: Record<string, string>) => string, } => {return {relative: (routeParams: {id:number, locale:'en'|'fr'}, queryParams?: Record<string, string>): string => appendQueryParams(replaceRouteParams('/users/{id}/{locale}', routeParams), queryParams), }};
export const path_users_route_with_requirements_and_defaults = (): { relative: (routeParams: {id:number, locale?:'en'|'fr'}, queryParams?: Record<string, string>) => string, } => {return {relative: (routeParams: {id:number, locale?:'en'|'fr'}, queryParams?: Record<string, string>): string => appendQueryParams(replaceRouteParams('/users/{id}/{locale}', {...{"locale":"en"}, ...routeParams}), queryParams), }};
export const path_users_route_with_requirements_and_null_defaults = (): { relative: (routeParams: {id:number, locale?:'en'|'fr'}, queryParams?: Record<string, string>) => string, } => {return {relative: (routeParams: {id:number, locale?:'en'|'fr'}, queryParams?: Record<string, string>): string => appendQueryParams(replaceRouteParams('/users/{id}/{locale}', {...{"locale":null}, ...routeParams}), queryParams), }};
export const path_generate_route_with_long_requirement_as_union = (): { relative: (routeParams: {intent:'new_email'|'email'|'print'|'printdebug'|'preview'|'preview_data'|'preview_text'|'gct.legalize', documents:string}, queryParams?: Record<string, string>) => string, } => {return {relative: (routeParams: {intent:'new_email'|'email'|'print'|'printdebug'|'preview'|'preview_data'|'preview_text'|'gct.legalize', documents:string}, queryParams?: Record<string, string>): string => appendQueryParams(replaceRouteParams('/generate/{intent}/{documents}', routeParams), queryParams), }};
export const path_generate_route_requirement_union_with_regex = (): { relative: (routeParams: {id:'new'|number}, queryParams?: Record<string, string>) => string, } => {return {relative: (routeParams: {id:'new'|number}, queryParams?: Record<string, string>): string => appendQueryParams(replaceRouteParams('/generate/{id}', routeParams), queryParams), }};
export const path_redirect_route_with_internal_defaults = (): { relative: (routeParams: {id:number}, queryParams?: Record<string, string>) => string, } => {return {relative: (routeParams: {id:number}, queryParams?: Record<string, string>): string => appendQueryParams(replaceRouteParams('/old/{id}', routeParams), queryParams), }};